[build]
  command = "npm install --legacy-peer-deps && npm run build -- --configuration production"
  publish = "dist/frontend/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200